INSERT INTO USER_SYSTEM(USER_ID, NAME, EMAIL, PASSWORD) VALUES(1, 'Admin', 'admin@email.com', '$2a$10$ouRVp.OkO9O2dmeRbVz6ieYd/XM2XSoSnvmxD1NzqQhjZlmwTtjxe');

INSERT INTO ROLE(ROLE_ID, NAME) VALUES(1, 'ROLE_ADMIN');
INSERT INTO ROLE(ROLE_ID, NAME) VALUES(2, 'ROLE_USER');

INSERT INTO ASSOC_USER_ROLE(USER_ID, ROLE_ID) VALUES(1, 1);